config/routes.rb
TaskTracingSystem::Application.routes.draw do
 resources :mywirelesses,:only=>['index','new','create','show']
 resources :callcenters,:only=>['index',"new","create"]
  post "callcenters/get_user"=>'callcenters#get_user'
  get "query" =>'query#index'
  post "query/query"
  match "summary" =>"summary#index"
  post "summary/index"
  match "summary/monthly_graph"=>"summary#monthly_graph"
  match  "summary/weekly_graph"
  match "summary/type_graph"
  match "summary/workload_graph"
  match "summary/waitting_graph"
  match "summary/workon_by_type_graph"
  match "summary/workon_by_staff_graph"
  match "summary/rank_graph"
  match "summary/rank_by_staff_graph"
  match "summary/callin_graph"
  resources :managements

  get "monitor" =>"monitor#index"
  get "monitor/list_not_taken_cases"
  get "monitor/list_more_hours_cases"
  get "monitor/list_working_cases"
  get "monitor/list_worked_more_days_cases"

  post 'mytasks/upgrade',:to=>'mytasks#upgrade'
  post 'mytasks/new',:to=>'mytasks#new'
  match 'mytasks/finished_tasks',:to=>"mytasks#finished_tasks"
  match "mytasks/verify_name"=> "mytasks#verify_name"
  resources :mytasks
  resources :mycases
  match 'comment/:id' =>"mycases#edit_comment", :as=>'comment'
  match 'closed_cases',:to=>"mycases#closed_cases",:as=>'closed_cases'
  resource :sessions, :only=>['new','create','destroy']
  match '/signin' ,:to =>'sessions#new'
  match  '/signout',:to=>'sessions#destroy'

   root :to => 'mycases#index'

end

app/controllers/mywirelesses_controller.rb
#--*-- encoding: UTF-8
class MywirelessesController < ApplicationController

  before_filter :login_required
  def index
    @myapps= Applicate.where(:user_id=>current_user.id).order("enabled_time DESC").paginate(:page=>params[:page],:per_page=>20)
  end

  def new
    @myapp=Applicate.new
  end

  def create
    @myapp=Applicate.new(params[:applicate])
    @myapp.user_id=current_user.id
    @myapp.name=current_user.name
    @myapp.department=current_user.department
    @myapp.enabled_time=Time.local(params[:applicate]['enabled_time(1i)'],params[:applicate]['enabled_time(2i)'],params[:applicate]['enabled_time(3i)'],params[:applicate]['enabled_time(4i)'],params[:applicate]['enabled_time(5i)'])

    i=0
    disabled_time=@myapp.enabled_time+3600*@myapp.during
    while i<@myapp.number
       code=Wireless.new
     code.enabled_time=@myapp.enabled_time
      code.disabled_time=disabled_time
          code.account=SecureRandom.random_number(1000000)
          code.password=SecureRandom.base64(6)
       @myapp.wirelesses<<code
    i+=1
  end
    respond_to do |format|
    if  @myapp.save
          message=WirelessNotice.wireless_notice(current_user,@myapp)
          message.deliver
          format.html { redirect_to mywireless_path @myapp ,notice: "已完成申请"}
    else
          format.html { render action: 'new'}
    end


    end
  end


  def show
    @myapp=Applicate.find(params[:id])
  end

end

app/helpers/mywirelesses_helper.rb
module MywirelessesHelper

end

app/views/mywirelesses/create.html.erb
<h1>Mywirelesses#create</h1>
<p>Find me in app/views/mywirelesses/create.html.erb</p>

app/views/mywirelesses/index.html.erb
<div class="wrap">
  <div class="my_case">
    <h2>我的无线使用申请</h2>
  </div>
  <div class="c_btn">
    <%= link_to "申请无线",{:action=>'new'},:method=>:get %></div>
  <div class='tit'>

    <h3>访客无线申请</h3>
  </div>
  <div class="c_table">
    <table cellspacing="0" cellpadding="0">
      <thead>
      <tr>
        <th>访客姓名</th>
        <th>访客单位</th>
        <th>申请原因</th>
        <th>申请数量</th>
        <th>启用时间</th>
        <th>使用时长</th>
      </tr></thead>
      <tbody>
      <% i=0 %>
      <% @myapps.each do |myapp| %>
          <% if i.even? %>
              <tr class="rol_d">
          <%else%>
              <tr class="rol_e">
          <%end%>
          <td><%= myapp.guest_name %></td>
          <td><%= myapp.guest_from %></td>
          <td><%= myapp.reason %></td>
          <td><%= myapp.number %></td>

          <td><%= myapp.enabled_time %></td>
          <td><%= myapp.during %></td>
          <td><%= link_to "详情",mywireless_path(myapp) %></td>

          </tr>
          <%i+=1%>
      <% end %></tbody >
    </table>    </div>
  <div class="more"> <%= will_paginate @myapps %></div>




</div>

app/views/mywirelesses/new.html.erb
<div class="wrap_new_table">
<div class="my_case">
  <h2>申请访客无线账号</h2>
</div>



<%= form_for @myapp,:url=>'/mywirelesses'  do |f| %>
    <% if @myapp.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@myapp.errors.count, "error") %> prohibited this appication from being saved:</h2>

          <ul>
            <% @myapp.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>

    <div class="new_table">
      <table cellspacing="0" cellpadding="0">

        <tr class="rol_d">
          <td class="r"> <%= f.label :guest_name,'访客姓名' %></td>
          <td class="l"><%= f.text_field :guest_name %></td>
        </tr>
        <tr class="rol_e">
          <td class="r"><%= f.label :guest_from,'访客单位' %></td>
          <td class="l"><%= f.text_field :guest_from %></td>
        </tr>
        <tr class="rol_d">
          <td class="r"> <%= f.label :number, "申请数量" %></td>
          <td class="l"> <%= f.select(:number,[[1,1],[2,2],[3,3],[4,4],[5,5]])  %></td>
        </tr>
        <tr class="rol_e">
          <td class="r"><%= f.label :enabled_time,"启用时间" %></td>
          <td class="l"> <%= f.datetime_select :enabled_time %></td>
        </tr>
        <tr class="rol_d">
          <td class="r"> <%= f.label :during,"使用时长" %></td>
          <td class="l"><%= f.select :during,[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12]] %>小时</td>
        </tr>

        <tr class="rol_e">
          <td class="r"><%= f.label :reason ,"申请原因"%></td>
          <td class="l"><%= f.text_area :reason,:rows=>6,:cols=>30 %> </td>
        </tr></table>
    </div>

    <div class="more">  <%= f.submit "提交" %>  </div>
<% end %>

<div class="more"   >
  <%= link_to '返回',:back %>
</div>

</div>

app/views/mywirelesses/show.html.erb
<div class="wrap">
  <div class="center">
    <p id="notice"><%= notice %></p>
    <p>
      <b>访客姓名:</b>
      <%= @myapp.guest_name %>
    </p>
    <p>
      <b>访客单位:</b>
      <%= @myapp.guest_from %>
    </p>
    <p>
      <b>申请原因:</b>
      <%= @myapp.reason %>
    </p>
    <p>
      <b>无线启用时间:</b>
      <%= @myapp.enabled_time %>
    </p>
    <p>
      <b>使用时长:</b>
      <%= @myapp.during %>  小时
    </p>
    <p>
      <b>无线账号及密码:</b>
    <li>
      <% @myapp.wirelesses.each do |item| %>
          <ul>
            登录名：<%=item.account %>
            密码:<%=item.password %>
          </ul>
      <%end%>
    </li>
    </p>
  </div>


  <div class="more">

    <%= link_to '返回', mywirelesses_path %>
  </div></div>