config/routes.rb
TaskTracingSystem::Application.routes.draw do
 resources :mywirelesses,:only=>['index','new','create','show']
 resources :callcenters,:only=>['index',"new","create"]
  post "callcenters/get_user"=>'callcenters#get_user'
  get "query" =>'query#index'
  post "query/query"
  match "summary" =>"summary#index"
  post "summary/index"
  match "summary/monthly_graph"=>"summary#monthly_graph"
  match  "summary/weekly_graph"
  match "summary/type_graph"
  match "summary/workload_graph"
  match "summary/waitting_graph"
  match "summary/workon_by_type_graph"
  match "summary/workon_by_staff_graph"
  match "summary/rank_graph"
  match "summary/rank_by_staff_graph"
  match "summary/callin_graph"
  resources :managements

  get "monitor" =>"monitor#index"
  get "monitor/list_not_taken_cases"
  get "monitor/list_more_hours_cases"
  get "monitor/list_working_cases"
  get "monitor/list_worked_more_days_cases"

  post 'mytasks/upgrade',:to=>'mytasks#upgrade'
  post 'mytasks/new',:to=>'mytasks#new'
  match 'mytasks/finished_tasks',:to=>"mytasks#finished_tasks"
  match "mytasks/verify_name"=> "mytasks#verify_name"
  resources :mytasks
  resources :mycases
  match 'comment/:id' =>"mycases#edit_comment", :as=>'comment'
  match 'closed_cases',:to=>"mycases#closed_cases",:as=>'closed_cases'
  resource :sessions, :only=>['new','create','destroy']
  match '/signin' ,:to =>'sessions#new'
  match  '/signout',:to=>'sessions#destroy'

   root :to => 'mycases#index'

end

app/controllers/mycases_controller.rb
#--encoding: UTF-8 --
class MycasesController < ApplicationController
  before_filter :login_required
  def index
        @my_opened_cases=ItCase.where( :user_id=>current_user.id,:status=>[ItCase::STATUSES['Waiting'], ItCase::STATUSES['Working']]) .order("opened_time ")
        @my_closed_cases=ItCase.where(:user_id=>current_user.id,:status=>ItCase::STATUSES['Closed']).limit(10)
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @it_cases }
        end
  end

  def show
    @it_case = ItCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @it_case }
    end
  end

  # GET /it_cases/new
  # GET /it_cases/new.json
  def new
    @it_case = ItCase.new

    @it_case.name=current_user.name
    @it_case.email=current_user.email
    @it_case.department=current_user.department
    @it_case.location= location_help
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @it_case }
    end
  end




  # GET /it_cases/1/edit
  def edit_comment
    @it_case = ItCase.find(params[:id])
    respond_to do |format| 
    if(@it_case.user_id==current_user.id)
      format.html
    else
     format.html{ redirect_to mycases_path, notice:"无权对它人工单评价"}
   end 
   end
     
  end



  # POST /it_cases
  # POST /it_cases.json
  def create
    @it_case = ItCase.new(params[:it_case])
    @it_case.user_id=current_user.id
    @it_case.ipaddress=request.remote_ip
    @it_case.status=ItCase::STATUSES['Waiting']
    @it_case.opened_time=Time.now
    @it_case.created_type='web'
    @it_case.creator_id=current_user.id
    respond_to do |format|
      if @it_case.save
        format.html { redirect_to mycases_path, notice: '工单已建立' }
        else
        format.html { render action: "new" }
       end
    end
  end

  # PUT /it_cases/1
  # PUT /it_cases/1.json
  def update
    @it_case = ItCase.find(params[:id])

    respond_to do |format|
      if @it_case.update_attributes(params[:it_case])
        format.html { redirect_to mycases_path, notice: '已完成评价' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @it_case.errors, status: :unprocessable_entity }
      end
    end
  end



  def closed_cases
      @my_closed_cases=ItCase.where(:user_id =>current_user.id,:status=>ItCase::STATUSES['Closed']).paginate(:page=>params[:page],:per_page=>60)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @it_cases }
      end
    end
end

app/helpers/mycases_helper.rb
module MycasesHelper
end

app/views/mycases/_form.html.erb

<div class='tit'>
  <h3>已完成工单</h3>
</div>
<div class="c_table">
  <table cellspacing="0" cellpadding="0">
    <thead>
    <tr>
      <th>问题类型</th>
      <th>问题描述</th>
      <th>提交时间</th>
      <th>处理状态</th>
      <th>完成时间</th>
      <th>处理情况</th>
      <th>评价</th>
      <th>评级</th>
    </tr> </thead>
    <tbody>
    <% i=0 %>
    <% @my_closed_cases.each do |it_case| %>
        <% if i.even? %>
            <tr class="rol_d">
        <%else%>
            <tr class="rol_e">
        <%end%>
          <td><%= it_case.casetype %></td>
          <td><%= it_case.description %></td>
          <td><%= it_case.opened_time %></td>
          <td><%= it_case.status %></td>
          <td><%= it_case.closed_time %></td>
          <td><%= it_case.result %></td>
          <td><%= it_case.comment %></td>
          <td><%= it_case.rank %></td>
          <td><%=link_to "评价",comment_path(it_case) %></td>
        </tr>
    <%i+=1%>
    <% end %>
    </tbody></table>
</div>

app/views/mycases/closed_cases.html.erb
<div class="wrap">
  <%= render "form" %>



     <%= will_paginate @my_closed_cases %><div class="more"><%= link_to "返回",mycases_path %>  </div></div>

app/views/mycases/edit_comment.erb


<div class="wrap_new_table">
  <div class="my_case">
<h2>评价工单</h2>
  </div>
<div class="new_table">


<%= form_for @it_case,:url=>mycase_path(@it_case) do |f| %>
    <% if @it_case.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@it_case.errors.count, "error") %> prohibited this it_case from being saved:</h2>

          <ul>
            <% @it_case.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <table cellspacing="0" cellpadding="0">
        <tr class="rol_d">
          <td class="r">问题类型</td>
          <td class="l"> <%= @it_case.casetype %>  </td>
        </tr>
        <tr class="rol_e">
          <td class="r">问题描述</td>
          <td class="l"> <%= @it_case.description %></td>
        </tr>

        <tr class="rol_d">
          <td class="r"><%=f.label :comment,"评价" %></td>
          <td class="l"><%= f.text_area :comment, :rows=>6,:cols=>30%></td>
          </tr>

        <tr class="rol_e">


          <td class="r"><%= f.label :rank,"评分" %> <%= f.hidden_field :rank %> </td>
          <td class="l">

            <div class="shop-rating">
                <ul class="rating-level" id="stars2">
                      <li><a href="javascript:void(0);" class="one-star" star:value="20">20</a></li>
                      <li><a href="javascript:void(0);" class="two-stars" star:value="40">40</a></li>
                       <li><a href="javascript:void(0);" class="three-stars" star:value="60">60</a></li>
                       <li><a href="javascript:void(0);" class="four-stars" star:value="80">80</a></li>
                        <li><a href="javascript:void(0);" class="five-stars" star:value="100">100</a></li>
                </ul>
                <span id="stars2-tips" class="result"></span>
              <script>
                  var TB = function() {
                      var T$ = function(id) { return document.getElementById(id) }
                      var T$$ = function(r, t) { return (r || document).getElementsByTagName(t) }
                      var Stars = function(cid, rid, hid, config) {
                          var lis = T$$(T$(cid), 'li'), curA;
                          for (var i = 0, len = lis.length; i < len; i++) {
                              lis[i]._val = i;
                              lis[i].onclick = function() {
                                  T$(rid).innerHTML = '<em>' + (T$(hid).value = T$$(this, 'a')[0].getAttribute('star:value')) + '分</em> - ' + config.info[this._val];
                                  curA = T$$(T$(cid), 'a')[T$(hid).value / config.step - 1];
                              };
                              lis[i].onmouseout = function() {
                                  curA && (curA.className += config.curcss);
                              }
                              lis[i].onmouseover = function() {
                                  curA && (curA.className = curA.className.replace(config.curcss, ''));
                              }
                          }
                      };
                      return {Stars: Stars}
                  }().Stars('stars2', 'stars2-tips', 'it_case_rank', {
                              'info' : ['极差', '不怎么好', '一般吧', '不错', '非常好'],
                              'curcss': ' current-rating',
                              'step': 20
                          });
              </script>

            </div>
         请对本次IT服务给与评分满分为5星100分 </td> </tr>
      </table>
      </div>

    <div class="more">
      <%= f.submit "提交" %>
    </div>
<% end %>

 <div class="more"> <%= link_to "返回",:back %> </div>
 </div>

app/views/mycases/index.html.erb
<div class="wrap">
<div class="my_case">
<h2>我的工单</h2>
</div>
  <div class="c_btn">
<%= link_to "创建工单",{:action=>'new'},:method=>:get %></div>
<div class='tit'>

    <h3>未完成工单</h3>
</div>
  <div class="c_table">
    <table cellspacing="0" cellpadding="0">
      <thead>
      <tr>
        <th>姓名</th>
        <th>部门</th>
        <th>问题类型</th>
        <th>问题描述</th>
        <th>提交时间</th>
        <th>处理状态</th>
      </tr></thead>
       <tbody>
       <% i=0 %>
      <% @my_opened_cases.each do |it_case| %>
           <% if i.even? %>
               <tr class="rol_d">
           <%else%>
               <tr class="rol_e">
           <%end%>
            <td><%= it_case.name %></td>
            <td><%= it_case.department %></td>
            <td><%= it_case.casetype %></td>
            <td><%= it_case.description %></td>

            <td><%= it_case.opened_time.to_s() %></td>
            <td><%= it_case.status %></td>

          </tr>
       <%i+=1%>
      <% end %></tbody >
    </table>    </div>




        <%= render "form" %>


      <div class="more"> <%=link_to "更多", closed_cases_path %></div>




</div>

app/views/mycases/new.html.erb
<div class="wrap_new_table">
  <div class="my_case">
    <h2>新建工单</h2>
  </div>



<%= form_for @it_case,:url=>'/mycases'  do |f| %>
    <% if @it_case.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(@it_case.errors.count, "error") %> prohibited this it_case from being saved:</h2>

          <ul>
            <% @it_case.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

  <% end %>

      <div class="new_table">
        <table cellspacing="0" cellpadding="0">

            <tr class="rol_d">
              <td class="r"> <%= f.label :name,'姓名' %></td>
              <td class="l"><%= f.text_field :name %></td>
            </tr>
            <tr class="rol_e">
              <td class="r"><%= f.label :department,'部门' %></td>
              <td class="l"><%= f.text_field :department %></td>
            </tr>
            <tr class="rol_d">
              <td class="r"> <%= f.label :email %></td>
              <td class="l"> <%= f.text_field :email %></td>
            </tr>
            <tr class="rol_e">
              <td class="r"><%= f.label :phone,"电话" %></td>
              <td class="l"> <%= f.text_field :phone %></td>
            </tr>
            <tr class="rol_d">
              <td class="r"> <%= f.label :location,"工作区" %></td>
              <td class="l"><%= f.select :location,ItCase::LOCATIONS,:selected=>location_help %></td>
            </tr>
            <tr class="rol_e">
              <td class="r"> <%= f.label :cubnum,"工位编号/位置描述" %></td>
              <td class="l"><%= f.text_field :cubnum %> 说明你的位置,使IT人员可以找到你</td>
            </tr>
            <tr class="rol_d">
              <td class="r"> <%= f.label :casetype,"问题类型" %></td>
              <td class="l"> <%= f.select :casetype,ItCase::CASETYPES %></td>
            </tr>
            <tr class="rol_e">
              <td class="r"><%= f.label :description ,"问题描述"%></td>
              <td class="l"><%= f.text_area :description,:rows=>6,:cols=>30 %> </td>
            </tr></table>
      </div>

        <div class="more">  <%= f.submit "提交" %>  </div>
<% end %>

  <div class="more"   >
<%= link_to '返回',:back %>
  </div>

</div>

app/views/mycases/show.html.erb
<%= render "/it_cases/show" %>
<%= link_to "返回",:back %>