config/routes.rb
TaskTracingSystem::Application.routes.draw do
 resources :mywirelesses,:only=>['index','new','create','show']
 resources :callcenters,:only=>['index',"new","create"]
  post "callcenters/get_user"=>'callcenters#get_user'
  get "query" =>'query#index'
  post "query/query"
  match "summary" =>"summary#index"
  post "summary/index"
  match "summary/monthly_graph"=>"summary#monthly_graph"
  match  "summary/weekly_graph"
  match "summary/type_graph"
  match "summary/workload_graph"
  match "summary/waitting_graph"
  match "summary/workon_by_type_graph"
  match "summary/workon_by_staff_graph"
  match "summary/rank_graph"
  match "summary/rank_by_staff_graph"
  match "summary/callin_graph"
  resources :managements

  get "monitor" =>"monitor#index"
  get "monitor/list_not_taken_cases"
  get "monitor/list_more_hours_cases"
  get "monitor/list_working_cases"
  get "monitor/list_worked_more_days_cases"

  post 'mytasks/upgrade',:to=>'mytasks#upgrade'
  post 'mytasks/new',:to=>'mytasks#new'
  match 'mytasks/finished_tasks',:to=>"mytasks#finished_tasks"
  match "mytasks/verify_name"=> "mytasks#verify_name"
  resources :mytasks
  resources :mycases
  match 'comment/:id' =>"mycases#edit_comment", :as=>'comment'
  match 'closed_cases',:to=>"mycases#closed_cases",:as=>'closed_cases'
  resource :sessions, :only=>['new','create','destroy']
  match '/signin' ,:to =>'sessions#new'
  match  '/signout',:to=>'sessions#destroy'

   root :to => 'mycases#index'

end

app/models/management.rb
#--*- encoding: UTF-8
class Management < ActiveRecord::Base
  has_many :rights
  before_validation(:on=>:create)  {get_userid }
#  validates_with LdapValidator, :attr=>:user
  validates_presence_of :userid,:user
  validates_uniqueness_of :userid

  CONTROLLER={"monitor"=>'监控',"mytasks"=>"处理工单","managements"=>"人员管理","callcenters"=>"电话工单","summary"=>"业务报表","query"=>'查询'}



  def myrights
    n={}
    unless self.rights.empty?
      self.rights.each  {|key| n[key.name]='on' }

      end
     n
  end

  def myrights=(list)
    unless self.rights.nil?
      self.rights.each do |item|
        self.rights.delete(item) unless list.has_key?(item.name)
       #logger.info "yes I got it"
      end

    end
    unless list.empty?
      list.each do |key, value|
          unless self.rights.index(key)
            myright=Right.new
            myright.name=key
            self.rights<<myright
          end

      end
    end


  end



   def self.has_rights(c_name, userid)

    my=self.where(:userid=>userid).first
   if my.nil?
        nil
    else
      my.rights.index{|x|x.name==c_name}
    end


  end

  private
  def get_userid()
    my=User.find_by_mail(self.email)
    self.userid=my.id unless my.nil?
  end

end

app/controllers/managements_controller.rb
# --*-- encoding: UTF-8
class ManagementsController < ApplicationController
  # GET /managements
  # GET /managements.json
before_filter :login_required,:has_right?
  def index
    @managements = Management.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managements }
    end
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
    @management = Management.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @management }
    end
  end

  # GET /managements/new
  # GET /managements/new.json
  def new
    @management = Management.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @management }
    end
  end

  # GET /managements/1/edit
  def edit
    @management = Management.find(params[:id])
  end

  # POST /managements
  # POST /managements.json
  def create
    @management = Management.new(params[:management])
    @management.email<<"@autonavi.com"


    respond_to do |format|
      if @management.save
        format.html { redirect_to @management, notice: '已完成添加' }
        format.json { render json: @management, status: :created, location: @management }
      else
        format.html { render action: "new" }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managements/1
  # PUT /managements/1.json
  def update
    @management = Management.find(params[:id])

    respond_to do |format|
      if @management.update_attributes(params[:management])
        format.html { redirect_to @management, notice: 'Management was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management = Management.find(params[:id])
    @management.destroy

    respond_to do |format|
      format.html { redirect_to managements_url }
      format.json { head :ok }
    end
  end
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/_form.html.erb
<%= form_for(@management) do |f| %>
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @management.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">

      <%= f.label :email %>
      <% if @management.email.nil? %>
          <%= f.text_field :email,:id=>'email' %>@autonavi.com
      <% else %>
          <%= f.text_field :email,:disabled=>'disabled'  %>
      <%  end %>
    </div>

  <div class="field">

    <%= f.label :user,"用户名" %>
    <% if @management.user.nil? %>
        <%= f.text_field :user,:id=>'name' %>
     <% else %>
    <%= f.text_field :user,:disabled=>'disabled'  %>
        <%  end %>
  </div>
    <div class="field">

      <%= f.label :department,"部门" %>
      <% if @management.department.nil? %>
          <%= f.text_field :department,:id=>'department' %>
      <% else %>
          <%= f.text_field :department,:disabled=>'disabled'  %>
      <%  end %>
    </div>
  <div class="field">
    <% Management::CONTROLLER.each do |key,value| %>
    <li>
      <ul>
        <%= check_box_tag "management[myrights][#{key}]",'on', !@management.myrights[key].nil?%>
        <%= label_tag value %>
      </ul>
    </li>
        <% end %>
  </div>

  <div class="actions">
    <%= f.submit "提交" %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<div class="wrap">
  <div class="my_case">
<h2>修改权限</h2></div>

<%= render 'form' %>

 <div class="more">
<%= link_to '返回', managements_path %></div>
</div>

app/views/managements/index.html.erb
<div class="wrap">
  <div class="my_case">
    <h2>人员管理</h2>
  </div>
  <div class="tit">
    <div class="c_table">
<table cellspacing="0" cellpadding="0">
  <thead>
  <tr>

    <th>用户名</th>
    <% Management::CONTROLLER.each do |key, value| %>
    <th><%= value%></th>
   <% end %>
       <th></th><th></th>
  </tr>
  </thead>
  <tbody>       <%i=0%>
<% @managements.each do |management| %>
      <% if i.even? %>
          <tr class="rol_d">
      <%else%>
          <tr class="rol_e">
      <%end%>

    <td><%= management.user %></td>
    <%  Management::CONTROLLER.each do |key, value| %>
     <td><%=  if management.myrights.has_key?(key); 'yes'; else 'no';end;  %></td>
        <%end%>

    <td><%= link_to '修改', edit_management_path(management) %></td>
    <td><%= link_to '删除', management, confirm: 'Are you sure?', method: :delete %></td>
  </tr>    <%i+=1%>
<% end %></tbody>
</table></div>
</div>


<div class="c_btn"><%= link_to '新建用户', new_management_path %>    </div>
</div>

app/views/managements/new.html.erb
<div class="wrap">
  <div class="my_case">
<h2>新建用户</h2>
</div>

<%= render 'form' %>
 <div class="more">
<%= link_to '返回', managements_path %></div>
</div>

app/views/managements/show.html.erb
<div class="wrap">
  <div class="center">
<p id="notice"><%= notice %></p>
<p>
  <b>用户名:</b>
  <%= @management.user %>
</p>
<p>
  <b>用户权限:</b>
  <li>
  <% @management.myrights.each do |key, value| %>
        <ul>
  <%= Management::CONTROLLER[key] %>
            </ul>
  <%end%>
</li>
</p>
</div>


 <div class="more">
<%= link_to "修改", edit_management_path(@management) %>
<%= link_to '返回', managements_path %>
</div></div>